data:
  data_path: "D:/Escritorio/TFG/Finance-AI/Datasets"
  output_path: "D:/Escritorio/TFG/Finance-AI/DataProcessed"
multi: False
tr_tst: [0.7, 0.8]
LSTM:
  window: 5
  epochs: 200
  batch_size: 750
  nhn: 50
  model: "stcklstm" # lstm, attlstm, stcklstm
