data:
  data_path: "/home/vvallejo/Finance-AI/datasets"
  output_path: "/home/vvallejo/Finance-AI/dataprocessed"
  date: '060124'
  filename_structure: "{ticker} US Equity_{date}.csv"

scenarios:
  - name: scenario_1
    tickers: ["AAPL", "ADBE", "AMZN", "AVGO", "CMCSA"]
    win: 5
    tr_tst: [0.7, 0.8]
    lahead: [1, 7, 14, 30, 90]
    n_features: 1
    n_itr: 10
    epochs: 256
    batch_size: 32
    nhn: 64
    LSTM:
      model: "lstm" # lstm, attlstm, stcklstm
    Transformer:
      model: "transformer"
      num_layers: 4
      num_heads: 16
      features: ["PX_LAST", "RSI_14D", "PX_TREND", "PX_VTREND"]

  - name: scenario_2
    tickers: ["AMZN", "GOOGL", "MSFT", "NVDA", "TSLA"]
    win: 50
    tr_tst: [0.75, 0.85]
    lahead: [1, 7, 14, 30, 90]
    n_features: 1
    n_itr: 10
    epochs: 256
    batch_size: 32
    nhn: 64
    LSTM:
      model: "stcklstm" # lstm, attlstm, stcklstm
    Transformer:
      model: "transformer"
      num_layers: 2
      num_heads: 4
      features: ["TWEET_POSTIVIE", "TWEET_NEGATIVE", "NEWS_POSITIVE", "NEWS_NEGATIVE"]

  - name: scenario_3
    tickers: ["AMZN", "PEP", "TMUS", "CSCO"]
    win: 2
    tr_tst: [0.75, 0.8]
    lahead: [1, 7, 14, 30, 90]
    n_features: 1
    n_itr: 10
    epochs: 256
    batch_size: 32
    nhn: 64
    LSTM:
      model: "attlstm" # lstm, attlstm, stcklstm
    Transformer:
      model: "transformer"
      num_layers: 2
      num_heads: 8
      features: ["PX_LAST", "PX_TREND", "VOLATILITY"]



